### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by SarahSorU** [LINCnil/pia-back#234]
Hi,
I'm trying to configure the LDAP authentification, but I can't use it.
I apply your instructions in the LDAP part. After that I would like to know how we use this LDAP authentification option.

As we don't have any explanation about the way we use it I tried this : 

1. Trying to use my LDAP account directly in the authenfication form like this : 
![image](https://github.com/LINCnil/pia-back/assets/151020731/05b8c6a3-e7a6-48ba-9a89-e86790b27aea)
But I have an error message : authentication.errors.sign_in.400

2. At this moment, I have used my local account to access at the application. I have searched for a LDAP option in the parameters menu. But you don't put any type of option like LDAP option, in the users parameters too.

Here my LDAP configuration :
![image](https://github.com/LINCnil/pia-back/assets/151020731/49d19182-7f9e-4c04-a017-1aad6273b87e)

![image](https://github.com/LINCnil/pia-back/assets/151020731/16623823-e313-4882-ba4c-7ea2bdf8e93f)

I would like to know how we can add all the LDAP users in the application?

Kind Regards,
Sarah.

**Comment by SarahSorU** [comment]
Hi,

I finally solved my issues, I can use the LDAP authentification but when we are logged all the information isn't filled in the form as the name and surname, how can I take these data in the LDAP? Is this features in developement?

Kind Regards,
Sarah.

**Comment by kevin-atnos** [comment]
Hello Sarah, 

What was the issue with your LDAP configuration?

What do you mean the information isn't logged? 
Were you previously using the PIA tool in local / front mode, without a backend?
If so, indeed now that you are in LDAP mode (with a backend), your PIA should be stored in a database instead of the local browser (indexDB).

On the homepage, you can export your PIAs and then import them in your new setup with LDAP so that they are re-stored but now in your database.

If you need any more help, please contact us at contact@atnos.com so that we can have a meeting and discuss this more easily.

Thank you very much, have a good day!

Regards,
