### ISSUE TITLE
Production mode does not provide GET / routes

### ISSUE THREAD

**Issue by romoloman** [LINCnil/pia-back#26]
I don't know whenever this is a feature or a bug but running pia-back in production mode does not show the default page when opened in the browser.
A 404 error is returned and in the production log the following error is returned:
I, [2018-03-20T10:55:23.718037 #11260]  INFO -- : [19d791e3-155e-4ad1-bfee-8d2dfa94ef59] Started GET "/" for xxx.xxx.xxx.xxx at 2018-03-20 10:55:23 +0100
F, [2018-03-20T10:55:23.719806 #11260] FATAL -- : [19d791e3-155e-4ad1-bfee-8d2dfa94ef59]   
F, [2018-03-20T10:55:23.719921 #11260] FATAL -- : [19d791e3-155e-4ad1-bfee-8d2dfa94ef59] ActionController::RoutingError (No route matches [GET] "/"):
F, [2018-03-20T10:55:23.720018 #11260] FATAL -- : [19d791e3-155e-4ad1-bfee-8d2dfa94ef59]   
F, [2018-03-20T10:55:23.720132 #11260] FATAL -- : [19d791e3-155e-4ad1-bfee-8d2dfa94ef59] actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'

**Comment by romoloman** [comment]
I had a look to: https://github.com/LINCnil/pia-back/issues/2
but 
RAILS_ENV=production bin/rake assets:precompile
is not a known task.

**Comment by brunto** [comment]
Do you still have this issue?

**Comment by klmj** [comment]
Yep, seen it on a fresh deployment with @kosmas58's docker image.

Need to add `/pias/` add the end of the pia-back url to workaround this (ex: `http://X.X.X.X:3000/pias/`).

**Comment by stept007** [comment]
I've also experienced that problem on my fresh installation after trying add URL to frontend:

F, [2018-10-04T16:00:02.430907 #9820] FATAL -- : [88189890-a4d1-45e9-8af9-53a26d80f4a9]   
F, [2018-10-04T16:00:02.431186 #9820] FATAL -- : [88189890-a4d1-45e9-8af9-53a26d80f4a9] **ActionController::RoutingError (No route matches [GET] "/")**:
F, [2018-10-04T16:00:02.431227 #9820] FATAL -- : [88189890-a4d1-45e9-8af9-53a26d80f4a9]   
F, [2018-10-04T16:00:02.431269 #9820] FATAL -- : [88189890-a4d1-45e9-8af9-53a26d80f4a9] actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'

And workaround above dosen't work, because then application tries to add another "/pias":
F, [2018-10-04T15:50:17.301292 #9820] FATAL -- : [7939019c-0fec-47a8-91fc-e84736177879]   
F, [2018-10-04T15:50:17.301419 #9820] FATAL -- : [7939019c-0fec-47a8-91fc-e84736177879] **ActionController::RoutingError (No route matches [POST] "/pias/pias")**:
F, [2018-10-04T15:50:17.301454 #9820] FATAL -- : [7939019c-0fec-47a8-91fc-e84736177879]   
F, [2018-10-04T15:50:17.301540 #9820] FATAL -- : [7939019c-0fec-47a8-91fc-e84736177879] actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'

**Comment by stept007** [comment]
My workaround is to add:
`root 'pias#example'`
in routes.rb

**Comment by berger-anthony** [comment]
systemd
ExecStart=/bin/bash -c "RAILS_SERVE_STATIC_FILES=true /opt/pia-back/bin/rails s -e production"

Il faut définir la variable RAILS_SERVE_STATIC_FILES
permettant de servir les fichiers static si apache non utilisé

**Comment by brunto** [comment]
I close this issue now, I think everything is ok.
